[settings]
private_keys = [
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
    "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
    "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
]

[ton_config]
chain_id = "-217"
type = "ton"
image = "ghcr.io/neodix42/mylocalton-docker:v3.97"

[ton_config.out]
family = "ton"

[ton_config.custom_env]
GLOBAL_ID = "-217"
NEXT_BLOCK_GENERATION_DELAY = "0.5"
VERSION_CAPABILITIES = "12"
