[settings]
private_keys = [
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
    "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
    "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
]

[evm_config_a]
chain_id = "1337"
image = "f4hrenh9it/foundry:latest"
port = "8545"
type = "anvil"

[evm_config_a.out]
family = "evm"

[evm_config_b]
chain_id = "2337"
image = "f4hrenh9it/foundry:latest"
port = "8546"
type = "anvil"

[evm_config_b.out]
family = "evm"
